### PR TITLE
linted

### PR DESCRIPTION
**Pull request by lsh-0**

### CODE REVIEW

**Comment by lsh-0** [comment]
```
[2020-02-11T02:47:20.375Z] PHPUnit 5.7.7 by Sebastian Bergmann and contributors.

[2020-02-11T02:47:20.375Z] 

[2020-02-11T02:47:20.375Z] .....PHP Fatal error:  Declaration of SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in /ext/jenkins-libraries-runner/workspace/ts-projects_api-problem-php_PR-6/vendor/sebastian/comparator/src/DOMNodeComparator.php on line 110

[2020-02-11T02:47:20.375Z] Fatal error: Declaration of SebastianBergmann\Comparator\DOMNodeComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false) must be compatible with SebastianBergmann\Comparator\ObjectComparator::assertEquals($expected, $actual, $delta = 0, $canonicalize = false, $ignoreCase = false, array &$processed = Array) in /ext/jenkins-libraries-runner/workspace/ts-projects_api-problem-php_PR-6/vendor/sebastian/comparator/src/DOMNodeComparator.php on line 110

script returned exit code 255
```

**Comment by lsh-0** [comment]
It seems a simple change to the order of these lines is causing the `Fatal error` we're seeing. I can replicate in Vagrant but don't have the faintest idea what is going on, unless `normalize_header` is shadowing something ... ?

Could you take a look @giorgiosironi ?

similar failure happening in:

* https://alfred.elifesciences.org/job/libraries/job/library-content-negotiator-php/11/console

**Comment by giorgiosironi** [comment]
https://github.com/elifesciences/api-problem-php/blob/master/project_tests.sh runs linting and then PHPUnit. If the linting fails, it doesn't get to PHPUnit failing which is the new error. We have seen this before so will look for the fix.

**Review by giorgiosironi — APPROVED** [review]

**Comment by lsh-0** [comment]
excellent, thanks for taking a look @giorgiosironi

**Pull request merged**
